// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPcDPLcVw0vzF5GjA1QLkgrfQEYcssFA8',
    appId: '1:244124690089:web:a8fa8f99ad9bdf4e28abb8',
    messagingSenderId: '244124690089',
    projectId: 'loginauthtest-5c250',
    authDomain: 'loginauthtest-5c250.firebaseapp.com',
    storageBucket: 'loginauthtest-5c250.appspot.com',
    measurementId: 'G-L3D9JXJXMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQi0lxrsECN9mI_0RuLeXcvTY8TieGeu8',
    appId: '1:244124690089:android:e426ef2d4ecd2c5c28abb8',
    messagingSenderId: '244124690089',
    projectId: 'loginauthtest-5c250',
    storageBucket: 'loginauthtest-5c250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJE8626DU081PUrAc1L0aobm-K4oz-F0',
    appId: '1:244124690089:ios:dd99a63fa158761128abb8',
    messagingSenderId: '244124690089',
    projectId: 'loginauthtest-5c250',
    storageBucket: 'loginauthtest-5c250.appspot.com',
    androidClientId: '244124690089-uum23ucrjogsidtfthedv3m6ses4a4e6.apps.googleusercontent.com',
    iosClientId: '244124690089-p68v6jtr0odeumc0na8e5scsn91mvf9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthFlutter',
  );
}
